libraries/deepseq_dist-install_VERSION = 1.4.1.1
libraries/deepseq_dist-install_PACKAGE_KEY = deeps_LbCWUlehDDeLxurARKDH5o
libraries/deepseq_dist-install_LIB_NAME = deepseq-1.4.1.1-LbCWUlehDDeLxurARKDH5o
libraries/deepseq_dist-install_MODULES = Control.DeepSeq
libraries/deepseq_dist-install_HIDDEN_MODULES = 
libraries/deepseq_dist-install_SYNOPSIS =Deep evaluation of data structures
libraries/deepseq_dist-install_HS_SRC_DIRS = .
libraries/deepseq_dist-install_DEPS = array-0.5.1.0 base-4.8.1.0
libraries/deepseq_dist-install_DEP_KEYS = array_E0sTtauuKsGDLZoT7lTbgZ base_GDytRqRVSUX7zckgKqJjgw
libraries/deepseq_dist-install_DEP_NAMES = array base
libraries/deepseq_dist-install_TRANSITIVE_DEPS = array-0.5.1.0 base-4.8.1.0 integer-gmp-1.0.0.0 ghc-prim-0.4.0.0 rts-1.0
libraries/deepseq_dist-install_TRANSITIVE_DEP_KEYS = array_E0sTtauuKsGDLZoT7lTbgZ base_GDytRqRVSUX7zckgKqJjgw integ_2aU3IZNMF9a7mQ0OzsZ0dS ghcpr_8TmvWUcS1U1IKHT0levwg3 rts
libraries/deepseq_dist-install_TRANSITIVE_DEP_NAMES = array base integer-gmp ghc-prim rts
libraries/deepseq_dist-install_INCLUDE_DIRS = 
libraries/deepseq_dist-install_INCLUDES = 
libraries/deepseq_dist-install_INSTALL_INCLUDES = 
libraries/deepseq_dist-install_EXTRA_LIBRARIES = 
libraries/deepseq_dist-install_EXTRA_LIBDIRS = 
libraries/deepseq_dist-install_C_SRCS  = 
libraries/deepseq_dist-install_CMM_SRCS  := $(addprefix cbits/,$(notdir $(wildcard libraries/deepseq/cbits/*.cmm)))
libraries/deepseq_dist-install_DATA_FILES = 
libraries/deepseq_dist-install_HC_OPTS = -Wall -XHaskell2010
libraries/deepseq_dist-install_CC_OPTS = 
libraries/deepseq_dist-install_CPP_OPTS = 
libraries/deepseq_dist-install_LD_OPTS = 
libraries/deepseq_dist-install_DEP_INCLUDE_DIRS_SINGLE_QUOTED = '/Users/mark/Projects/ghc-7.10.2/libraries/base/include' '/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/include' '/Users/mark/Projects/ghc-7.10.2/rts/dist/build' '/Users/mark/Projects/ghc-7.10.2/includes' '/Users/mark/Projects/ghc-7.10.2/includes/dist-derivedconstants/header'
libraries/deepseq_dist-install_DEP_CC_OPTS = 
libraries/deepseq_dist-install_DEP_LIB_DIRS_SINGLE_QUOTED = '/Users/mark/Projects/ghc-7.10.2/libraries/array/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/base/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/ghc-prim/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/rts/dist/build'
libraries/deepseq_dist-install_DEP_LIB_DIRS_SEARCHPATH = /Users/mark/Projects/ghc-7.10.2/libraries/array/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/base/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/ghc-prim/dist-install/build:/Users/mark/Projects/ghc-7.10.2/rts/dist/build
libraries/deepseq_dist-install_DEP_LIB_REL_DIRS = libraries/array/dist-install/build libraries/base/dist-install/build libraries/integer-gmp2/dist-install/build libraries/ghc-prim/dist-install/build rts/dist/build
libraries/deepseq_dist-install_DEP_LIB_REL_DIRS_SEARCHPATH = libraries/array/dist-install/build:libraries/base/dist-install/build:libraries/integer-gmp2/dist-install/build:libraries/ghc-prim/dist-install/build:rts/dist/build
libraries/deepseq_dist-install_DEP_EXTRA_LIBS = iconv m dl
libraries/deepseq_dist-install_DEP_LD_OPTS = 
libraries/deepseq_dist-install_BUILD_GHCI_LIB = NO

$(eval $(libraries/deepseq_PACKAGE_MAGIC))
