utils/dll-split_dist-install_VERSION = 0.1
utils/dll-split_dist-install_PACKAGE_KEY = dllsp_41YAlm5aJNhFR7w6XNXrb5
utils/dll-split_dist-install_LIB_NAME = dll-split-0.1-41YAlm5aJNhFR7w6XNXrb5
utils/dll-split_dist-install_MODULES = Main
utils/dll-split_dist-install_HIDDEN_MODULES = 
utils/dll-split_dist-install_SYNOPSIS =XXX
utils/dll-split_dist-install_HS_SRC_DIRS = .
utils/dll-split_dist-install_DEPS = base-4.8.1.0 containers-0.5.6.2 filepath-1.4.0.0
utils/dll-split_dist-install_DEP_KEYS = base_GDytRqRVSUX7zckgKqJjgw conta_LKCPrTJwOTOLk4OU37YmeN filep_KsGE6pHE5eZHSN90ZVax6A
utils/dll-split_dist-install_DEP_NAMES = base containers filepath
utils/dll-split_dist-install_TRANSITIVE_DEPS = filepath-1.4.0.0 containers-0.5.6.2 deepseq-1.4.1.1 array-0.5.1.0 base-4.8.1.0 integer-gmp-1.0.0.0 ghc-prim-0.4.0.0 rts-1.0
utils/dll-split_dist-install_TRANSITIVE_DEP_KEYS = filep_KsGE6pHE5eZHSN90ZVax6A conta_LKCPrTJwOTOLk4OU37YmeN deeps_LbCWUlehDDeLxurARKDH5o array_E0sTtauuKsGDLZoT7lTbgZ base_GDytRqRVSUX7zckgKqJjgw integ_2aU3IZNMF9a7mQ0OzsZ0dS ghcpr_8TmvWUcS1U1IKHT0levwg3 rts
utils/dll-split_dist-install_TRANSITIVE_DEP_NAMES = filepath containers deepseq array base integer-gmp ghc-prim rts
utils/dll-split_dist-install_INCLUDE_DIRS = 
utils/dll-split_dist-install_INCLUDES = 
utils/dll-split_dist-install_INSTALL_INCLUDES = 
utils/dll-split_dist-install_EXTRA_LIBRARIES = 
utils/dll-split_dist-install_EXTRA_LIBDIRS = 
utils/dll-split_dist-install_C_SRCS  = 
utils/dll-split_dist-install_CMM_SRCS  := $(addprefix cbits/,$(notdir $(wildcard utils/dll-split/cbits/*.cmm)))
utils/dll-split_dist-install_DATA_FILES = 
utils/dll-split_dist-install_HC_OPTS = -XHaskell2010
utils/dll-split_dist-install_CC_OPTS = 
utils/dll-split_dist-install_CPP_OPTS = 
utils/dll-split_dist-install_LD_OPTS = 
utils/dll-split_dist-install_DEP_INCLUDE_DIRS_SINGLE_QUOTED = '/Users/mark/Projects/ghc-7.10.2/libraries/containers/include' '/Users/mark/Projects/ghc-7.10.2/libraries/base/include' '/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/include' '/Users/mark/Projects/ghc-7.10.2/rts/dist/build' '/Users/mark/Projects/ghc-7.10.2/includes' '/Users/mark/Projects/ghc-7.10.2/includes/dist-derivedconstants/header'
utils/dll-split_dist-install_DEP_CC_OPTS = 
utils/dll-split_dist-install_DEP_LIB_DIRS_SINGLE_QUOTED = '/Users/mark/Projects/ghc-7.10.2/libraries/filepath/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/containers/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/deepseq/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/array/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/base/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/ghc-prim/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/rts/dist/build'
utils/dll-split_dist-install_DEP_LIB_DIRS_SEARCHPATH = /Users/mark/Projects/ghc-7.10.2/libraries/filepath/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/containers/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/deepseq/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/array/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/base/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/ghc-prim/dist-install/build:/Users/mark/Projects/ghc-7.10.2/rts/dist/build
utils/dll-split_dist-install_DEP_LIB_REL_DIRS = libraries/filepath/dist-install/build libraries/containers/dist-install/build libraries/deepseq/dist-install/build libraries/array/dist-install/build libraries/base/dist-install/build libraries/integer-gmp2/dist-install/build libraries/ghc-prim/dist-install/build rts/dist/build
utils/dll-split_dist-install_DEP_LIB_REL_DIRS_SEARCHPATH = libraries/filepath/dist-install/build:libraries/containers/dist-install/build:libraries/deepseq/dist-install/build:libraries/array/dist-install/build:libraries/base/dist-install/build:libraries/integer-gmp2/dist-install/build:libraries/ghc-prim/dist-install/build:rts/dist/build
utils/dll-split_dist-install_DEP_EXTRA_LIBS = iconv m dl
utils/dll-split_dist-install_DEP_LD_OPTS = 
utils/dll-split_dist-install_BUILD_GHCI_LIB = NO

$(eval $(utils/dll-split_PACKAGE_MAGIC))
