/Users/mark/Projects/ghc-7.10.2/inplace/lib/bin/haddock -B/Users/mark/Projects/ghc-7.10.2/inplace/lib -l/Users/mark/Projects/ghc-7.10.2/inplace/lib --odir=libraries/bin-package-db/dist-install/doc/html/bin-package-db --no-tmp-comp-dir --dump-interface=libraries/bin-package-db/dist-install/doc/html/bin-package-db/bin-package-db.haddock --html --hoogle --title=bin-package-db-0.0.0.0: The GHC compiler's view of the GHC package database format --prologue=libraries/bin-package-db/dist-install/haddock-prologue.txt --read-interface=../base-4.8.1.0,../base-4.8.1.0/src/%{MODULE/./-}.html#%{NAME},libraries/base/dist-install/doc/html/base/base.haddock --read-interface=../binary-0.7.5.0,../binary-0.7.5.0/src/%{MODULE/./-}.html#%{NAME},libraries/binary/dist-install/doc/html/binary/binary.haddock --read-interface=../bytestring-0.10.6.0,../bytestring-0.10.6.0/src/%{MODULE/./-}.html#%{NAME},libraries/bytestring/dist-install/doc/html/bytestring/bytestring.haddock --read-interface=../directory-1.2.2.0,../directory-1.2.2.0/src/%{MODULE/./-}.html#%{NAME},libraries/directory/dist-install/doc/html/directory/directory.haddock --read-interface=../filepath-1.4.0.0,../filepath-1.4.0.0/src/%{MODULE/./-}.html#%{NAME},libraries/filepath/dist-install/doc/html/filepath/filepath.haddock --optghc=-hisuf --optghc=dyn_hi --optghc=-osuf --optghc=dyn_o --optghc=-hcsuf --optghc=dyn_hc --optghc=-fPIC --optghc=-dynamic --optghc=-H32m --optghc=-O --optghc=-this-package-key --optghc=binpa_HeqFuAPxbeUAPK6hSBHejU --optghc=-hide-all-packages --optghc=-i --optghc=-ilibraries/bin-package-db/. --optghc=-ilibraries/bin-package-db/dist-install/build --optghc=-ilibraries/bin-package-db/dist-install/build/autogen --optghc=-Ilibraries/bin-package-db/dist-install/build --optghc=-Ilibraries/bin-package-db/dist-install/build/autogen --optghc=-Ilibraries/bin-package-db/. --optghc=-optP-include --optghc=-optPlibraries/bin-package-db/dist-install/build/autogen/cabal_macros.h --optghc=-package-key --optghc=base_GDytRqRVSUX7zckgKqJjgw --optghc=-package-key --optghc=binar_IvYoLp9H6Xy3zEH13MmZwd --optghc=-package-key --optghc=bytes_6elQVSg5cWdFrvRnfxTUrH --optghc=-package-key --optghc=direc_KowvXytSqazBcvN7MGpFtg --optghc=-package-key --optghc=filep_KsGE6pHE5eZHSN90ZVax6A --optghc=-XHaskell2010 --optghc=-O2 --optghc=-no-user-package-db --optghc=-rtsopts --optghc=-odir --optghc=libraries/bin-package-db/dist-install/build --optghc=-hidir --optghc=libraries/bin-package-db/dist-install/build --optghc=-stubdir --optghc=libraries/bin-package-db/dist-install/build --source-module=src/%{MODULE/./-}.html --source-entity=src/%{MODULE/./-}.html#%{NAME} libraries/bin-package-db/./GHC/PackageDb.hs +RTS -tlibraries/bin-package-db/dist-install/doc/html/bin-package-db/bin-package-db.haddock.t --machine-readable 
 [("bytes allocated", "423446472")
 ,("num_GCs", "485")
 ,("average_bytes_used", "16306757")
 ,("max_bytes_used", "42227632")
 ,("num_byte_usage_samples", "6")
 ,("peak_megabytes_allocated", "84")
 ,("init_cpu_seconds", "0.001")
 ,("init_wall_seconds", "0.007")
 ,("mutator_cpu_seconds", "0.425")
 ,("mutator_wall_seconds", "0.880")
 ,("GC_cpu_seconds", "0.769")
 ,("GC_wall_seconds", "1.193")
 ]
