libraries/array_dist-install_VERSION = 0.5.1.0
libraries/array_dist-install_PACKAGE_KEY = array_E0sTtauuKsGDLZoT7lTbgZ
libraries/array_dist-install_LIB_NAME = array-0.5.1.0-E0sTtauuKsGDLZoT7lTbgZ
libraries/array_dist-install_MODULES = Data.Array Data.Array.Base Data.Array.IArray Data.Array.IO Data.Array.IO.Safe Data.Array.IO.Internals Data.Array.MArray Data.Array.MArray.Safe Data.Array.ST Data.Array.ST.Safe Data.Array.Storable Data.Array.Storable.Safe Data.Array.Storable.Internals Data.Array.Unboxed Data.Array.Unsafe
libraries/array_dist-install_HIDDEN_MODULES = 
libraries/array_dist-install_SYNOPSIS =Mutable and immutable arrays
libraries/array_dist-install_HS_SRC_DIRS = .
libraries/array_dist-install_DEPS = base-4.8.1.0
libraries/array_dist-install_DEP_KEYS = base_GDytRqRVSUX7zckgKqJjgw
libraries/array_dist-install_DEP_NAMES = base
libraries/array_dist-install_TRANSITIVE_DEPS = base-4.8.1.0 integer-gmp-1.0.0.0 ghc-prim-0.4.0.0 rts-1.0
libraries/array_dist-install_TRANSITIVE_DEP_KEYS = base_GDytRqRVSUX7zckgKqJjgw integ_2aU3IZNMF9a7mQ0OzsZ0dS ghcpr_8TmvWUcS1U1IKHT0levwg3 rts
libraries/array_dist-install_TRANSITIVE_DEP_NAMES = base integer-gmp ghc-prim rts
libraries/array_dist-install_INCLUDE_DIRS = 
libraries/array_dist-install_INCLUDES = 
libraries/array_dist-install_INSTALL_INCLUDES = 
libraries/array_dist-install_EXTRA_LIBRARIES = 
libraries/array_dist-install_EXTRA_LIBDIRS = 
libraries/array_dist-install_C_SRCS  = 
libraries/array_dist-install_CMM_SRCS  := $(addprefix cbits/,$(notdir $(wildcard libraries/array/cbits/*.cmm)))
libraries/array_dist-install_DATA_FILES = 
libraries/array_dist-install_HC_OPTS = -Wall -XHaskell2010
libraries/array_dist-install_CC_OPTS = 
libraries/array_dist-install_CPP_OPTS = 
libraries/array_dist-install_LD_OPTS = 
libraries/array_dist-install_DEP_INCLUDE_DIRS_SINGLE_QUOTED = '/Users/mark/Projects/ghc-7.10.2/libraries/base/include' '/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/include' '/Users/mark/Projects/ghc-7.10.2/rts/dist/build' '/Users/mark/Projects/ghc-7.10.2/includes' '/Users/mark/Projects/ghc-7.10.2/includes/dist-derivedconstants/header'
libraries/array_dist-install_DEP_CC_OPTS = 
libraries/array_dist-install_DEP_LIB_DIRS_SINGLE_QUOTED = '/Users/mark/Projects/ghc-7.10.2/libraries/base/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/ghc-prim/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/rts/dist/build'
libraries/array_dist-install_DEP_LIB_DIRS_SEARCHPATH = /Users/mark/Projects/ghc-7.10.2/libraries/base/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/ghc-prim/dist-install/build:/Users/mark/Projects/ghc-7.10.2/rts/dist/build
libraries/array_dist-install_DEP_LIB_REL_DIRS = libraries/base/dist-install/build libraries/integer-gmp2/dist-install/build libraries/ghc-prim/dist-install/build rts/dist/build
libraries/array_dist-install_DEP_LIB_REL_DIRS_SEARCHPATH = libraries/base/dist-install/build:libraries/integer-gmp2/dist-install/build:libraries/ghc-prim/dist-install/build:rts/dist/build
libraries/array_dist-install_DEP_EXTRA_LIBS = iconv m dl
libraries/array_dist-install_DEP_LD_OPTS = 
libraries/array_dist-install_BUILD_GHCI_LIB = NO

$(eval $(libraries/array_PACKAGE_MAGIC))
