/Users/mark/Projects/ghc-7.10.2/inplace/lib/bin/haddock -B/Users/mark/Projects/ghc-7.10.2/inplace/lib -l/Users/mark/Projects/ghc-7.10.2/inplace/lib --odir=libraries/xhtml/dist-install/doc/html/xhtml --no-tmp-comp-dir --dump-interface=libraries/xhtml/dist-install/doc/html/xhtml/xhtml.haddock --html --hoogle --title=xhtml-3000.2.1: An XHTML combinator library --prologue=libraries/xhtml/dist-install/haddock-prologue.txt --hide=Text.XHtml.Strict.Attributes --hide=Text.XHtml.Strict.Elements --hide=Text.XHtml.Frameset.Attributes --hide=Text.XHtml.Frameset.Elements --hide=Text.XHtml.Transitional.Attributes --hide=Text.XHtml.Transitional.Elements --hide=Text.XHtml.BlockTable --hide=Text.XHtml.Extras --hide=Text.XHtml.Internals --read-interface=../base-4.8.1.0,../base-4.8.1.0/src/%{MODULE/./-}.html#%{NAME},libraries/base/dist-install/doc/html/base/base.haddock --optghc=-hisuf --optghc=dyn_hi --optghc=-osuf --optghc=dyn_o --optghc=-hcsuf --optghc=dyn_hc --optghc=-fPIC --optghc=-dynamic --optghc=-H32m --optghc=-O --optghc=-this-package-key --optghc=xhtml_FxPylgBilld3tRCpn3X21N --optghc=-hide-all-packages --optghc=-i --optghc=-ilibraries/xhtml/. --optghc=-ilibraries/xhtml/dist-install/build --optghc=-ilibraries/xhtml/dist-install/build/autogen --optghc=-Ilibraries/xhtml/dist-install/build --optghc=-Ilibraries/xhtml/dist-install/build/autogen --optghc=-Ilibraries/xhtml/. --optghc=-optP-include --optghc=-optPlibraries/xhtml/dist-install/build/autogen/cabal_macros.h --optghc=-package-key --optghc=base_GDytRqRVSUX7zckgKqJjgw --optghc=-Wall --optghc=-XHaskell98 --optghc=-XCPP --optghc=-O2 --optghc=-no-user-package-db --optghc=-rtsopts --optghc=-odir --optghc=libraries/xhtml/dist-install/build --optghc=-hidir --optghc=libraries/xhtml/dist-install/build --optghc=-stubdir --optghc=libraries/xhtml/dist-install/build --source-module=src/%{MODULE/./-}.html --source-entity=src/%{MODULE/./-}.html#%{NAME} libraries/xhtml/./Text/XHtml.hs libraries/xhtml/./Text/XHtml/Frameset.hs libraries/xhtml/./Text/XHtml/Strict.hs libraries/xhtml/./Text/XHtml/Transitional.hs libraries/xhtml/./Text/XHtml/Debug.hs libraries/xhtml/./Text/XHtml/Table.hs libraries/xhtml/./Text/XHtml/Strict/Attributes.hs libraries/xhtml/./Text/XHtml/Strict/Elements.hs libraries/xhtml/./Text/XHtml/Frameset/Attributes.hs libraries/xhtml/./Text/XHtml/Frameset/Elements.hs libraries/xhtml/./Text/XHtml/Transitional/Attributes.hs libraries/xhtml/./Text/XHtml/Transitional/Elements.hs libraries/xhtml/./Text/XHtml/BlockTable.hs libraries/xhtml/./Text/XHtml/Extras.hs libraries/xhtml/./Text/XHtml/Internals.hs +RTS -tlibraries/xhtml/dist-install/doc/html/xhtml/xhtml.haddock.t --machine-readable 
 [("bytes allocated", "564154336")
 ,("num_GCs", "422")
 ,("average_bytes_used", "13061566")
 ,("max_bytes_used", "25998776")
 ,("num_byte_usage_samples", "6")
 ,("peak_megabytes_allocated", "70")
 ,("init_cpu_seconds", "0.000")
 ,("init_wall_seconds", "0.001")
 ,("mutator_cpu_seconds", "0.523")
 ,("mutator_wall_seconds", "1.936")
 ,("GC_cpu_seconds", "0.581")
 ,("GC_wall_seconds", "0.938")
 ]
