/Users/mark/Projects/ghc-7.10.2/inplace/lib/bin/haddock -B/Users/mark/Projects/ghc-7.10.2/inplace/lib -l/Users/mark/Projects/ghc-7.10.2/inplace/lib --odir=libraries/hpc/dist-install/doc/html/hpc --no-tmp-comp-dir --dump-interface=libraries/hpc/dist-install/doc/html/hpc/hpc.haddock --html --hoogle --title=hpc-0.6.0.2: Code Coverage Library for Haskell --prologue=libraries/hpc/dist-install/haddock-prologue.txt --read-interface=../base-4.8.1.0,../base-4.8.1.0/src/%{MODULE/./-}.html#%{NAME},libraries/base/dist-install/doc/html/base/base.haddock --read-interface=../containers-0.5.6.2,../containers-0.5.6.2/src/%{MODULE/./-}.html#%{NAME},libraries/containers/dist-install/doc/html/containers/containers.haddock --read-interface=../directory-1.2.2.0,../directory-1.2.2.0/src/%{MODULE/./-}.html#%{NAME},libraries/directory/dist-install/doc/html/directory/directory.haddock --read-interface=../filepath-1.4.0.0,../filepath-1.4.0.0/src/%{MODULE/./-}.html#%{NAME},libraries/filepath/dist-install/doc/html/filepath/filepath.haddock --read-interface=../time-1.5.0.1,../time-1.5.0.1/src/%{MODULE/./-}.html#%{NAME},libraries/time/dist-install/doc/html/time/time.haddock --optghc=-hisuf --optghc=dyn_hi --optghc=-osuf --optghc=dyn_o --optghc=-hcsuf --optghc=dyn_hc --optghc=-fPIC --optghc=-dynamic --optghc=-H32m --optghc=-O --optghc=-this-package-key --optghc=hpc_EoBo26ZW1TCDX9aShnDKTF --optghc=-hide-all-packages --optghc=-i --optghc=-ilibraries/hpc/. --optghc=-ilibraries/hpc/dist-install/build --optghc=-ilibraries/hpc/dist-install/build/autogen --optghc=-Ilibraries/hpc/dist-install/build --optghc=-Ilibraries/hpc/dist-install/build/autogen --optghc=-Ilibraries/hpc/. --optghc=-optP-include --optghc=-optPlibraries/hpc/dist-install/build/autogen/cabal_macros.h --optghc=-package-key --optghc=base_GDytRqRVSUX7zckgKqJjgw --optghc=-package-key --optghc=conta_LKCPrTJwOTOLk4OU37YmeN --optghc=-package-key --optghc=direc_KowvXytSqazBcvN7MGpFtg --optghc=-package-key --optghc=filep_KsGE6pHE5eZHSN90ZVax6A --optghc=-package-key --optghc=time_AXTdBF9VRQoBOqJT6qtmVH --optghc=-Wall --optghc=-XHaskell98 --optghc=-O2 --optghc=-no-user-package-db --optghc=-rtsopts --optghc=-odir --optghc=libraries/hpc/dist-install/build --optghc=-hidir --optghc=libraries/hpc/dist-install/build --optghc=-stubdir --optghc=libraries/hpc/dist-install/build --source-module=src/%{MODULE/./-}.html --source-entity=src/%{MODULE/./-}.html#%{NAME} libraries/hpc/./Trace/Hpc/Util.hs libraries/hpc/./Trace/Hpc/Mix.hs libraries/hpc/./Trace/Hpc/Tix.hs libraries/hpc/dist-install/build/Trace/Hpc/Reflect.hs +RTS -tlibraries/hpc/dist-install/doc/html/hpc/hpc.haddock.t --machine-readable 
 [("bytes allocated", "414190984")
 ,("num_GCs", "481")
 ,("average_bytes_used", "15850250")
 ,("max_bytes_used", "41387864")
 ,("num_byte_usage_samples", "6")
 ,("peak_megabytes_allocated", "81")
 ,("init_cpu_seconds", "0.000")
 ,("init_wall_seconds", "0.002")
 ,("mutator_cpu_seconds", "0.441")
 ,("mutator_wall_seconds", "0.952")
 ,("GC_cpu_seconds", "0.774")
 ,("GC_wall_seconds", "1.067")
 ]
