libraries/xhtml_dist-install_VERSION = 3000.2.1
libraries/xhtml_dist-install_PACKAGE_KEY = xhtml_FxPylgBilld3tRCpn3X21N
libraries/xhtml_dist-install_LIB_NAME = xhtml-3000.2.1-FxPylgBilld3tRCpn3X21N
libraries/xhtml_dist-install_MODULES = Text.XHtml Text.XHtml.Frameset Text.XHtml.Strict Text.XHtml.Transitional Text.XHtml.Debug Text.XHtml.Table Text.XHtml.Strict.Attributes Text.XHtml.Strict.Elements Text.XHtml.Frameset.Attributes Text.XHtml.Frameset.Elements Text.XHtml.Transitional.Attributes Text.XHtml.Transitional.Elements Text.XHtml.BlockTable Text.XHtml.Extras Text.XHtml.Internals
libraries/xhtml_dist-install_HIDDEN_MODULES = Text.XHtml.Strict.Attributes Text.XHtml.Strict.Elements Text.XHtml.Frameset.Attributes Text.XHtml.Frameset.Elements Text.XHtml.Transitional.Attributes Text.XHtml.Transitional.Elements Text.XHtml.BlockTable Text.XHtml.Extras Text.XHtml.Internals
libraries/xhtml_dist-install_SYNOPSIS =An XHTML combinator library
libraries/xhtml_dist-install_HS_SRC_DIRS = .
libraries/xhtml_dist-install_DEPS = base-4.8.1.0
libraries/xhtml_dist-install_DEP_KEYS = base_GDytRqRVSUX7zckgKqJjgw
libraries/xhtml_dist-install_DEP_NAMES = base
libraries/xhtml_dist-install_TRANSITIVE_DEPS = base-4.8.1.0 integer-gmp-1.0.0.0 ghc-prim-0.4.0.0 rts-1.0
libraries/xhtml_dist-install_TRANSITIVE_DEP_KEYS = base_GDytRqRVSUX7zckgKqJjgw integ_2aU3IZNMF9a7mQ0OzsZ0dS ghcpr_8TmvWUcS1U1IKHT0levwg3 rts
libraries/xhtml_dist-install_TRANSITIVE_DEP_NAMES = base integer-gmp ghc-prim rts
libraries/xhtml_dist-install_INCLUDE_DIRS = 
libraries/xhtml_dist-install_INCLUDES = 
libraries/xhtml_dist-install_INSTALL_INCLUDES = 
libraries/xhtml_dist-install_EXTRA_LIBRARIES = 
libraries/xhtml_dist-install_EXTRA_LIBDIRS = 
libraries/xhtml_dist-install_C_SRCS  = 
libraries/xhtml_dist-install_CMM_SRCS  := $(addprefix cbits/,$(notdir $(wildcard libraries/xhtml/cbits/*.cmm)))
libraries/xhtml_dist-install_DATA_FILES = 
libraries/xhtml_dist-install_HC_OPTS = -Wall -XHaskell98 -XCPP
libraries/xhtml_dist-install_CC_OPTS = 
libraries/xhtml_dist-install_CPP_OPTS = 
libraries/xhtml_dist-install_LD_OPTS = 
libraries/xhtml_dist-install_DEP_INCLUDE_DIRS_SINGLE_QUOTED = '/Users/mark/Projects/ghc-7.10.2/libraries/base/include' '/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/include' '/Users/mark/Projects/ghc-7.10.2/rts/dist/build' '/Users/mark/Projects/ghc-7.10.2/includes' '/Users/mark/Projects/ghc-7.10.2/includes/dist-derivedconstants/header'
libraries/xhtml_dist-install_DEP_CC_OPTS = 
libraries/xhtml_dist-install_DEP_LIB_DIRS_SINGLE_QUOTED = '/Users/mark/Projects/ghc-7.10.2/libraries/base/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/ghc-prim/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/rts/dist/build'
libraries/xhtml_dist-install_DEP_LIB_DIRS_SEARCHPATH = /Users/mark/Projects/ghc-7.10.2/libraries/base/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/ghc-prim/dist-install/build:/Users/mark/Projects/ghc-7.10.2/rts/dist/build
libraries/xhtml_dist-install_DEP_LIB_REL_DIRS = libraries/base/dist-install/build libraries/integer-gmp2/dist-install/build libraries/ghc-prim/dist-install/build rts/dist/build
libraries/xhtml_dist-install_DEP_LIB_REL_DIRS_SEARCHPATH = libraries/base/dist-install/build:libraries/integer-gmp2/dist-install/build:libraries/ghc-prim/dist-install/build:rts/dist/build
libraries/xhtml_dist-install_DEP_EXTRA_LIBS = iconv m dl
libraries/xhtml_dist-install_DEP_LD_OPTS = 
libraries/xhtml_dist-install_BUILD_GHCI_LIB = NO

$(eval $(libraries/xhtml_PACKAGE_MAGIC))
