/Users/mark/Projects/ghc-7.10.2/inplace/lib/bin/haddock -B/Users/mark/Projects/ghc-7.10.2/inplace/lib -l/Users/mark/Projects/ghc-7.10.2/inplace/lib --odir=libraries/template-haskell/dist-install/doc/html/template-haskell --no-tmp-comp-dir --dump-interface=libraries/template-haskell/dist-install/doc/html/template-haskell/template-haskell.haddock --html --hoogle --title=template-haskell-2.10.0.0: Support library for Template Haskell --prologue=libraries/template-haskell/dist-install/haddock-prologue.txt --hide=Language.Haskell.TH.Lib.Map --read-interface=../base-4.8.1.0,../base-4.8.1.0/src/%{MODULE/./-}.html#%{NAME},libraries/base/dist-install/doc/html/base/base.haddock --read-interface=../pretty-1.1.2.0,../pretty-1.1.2.0/src/%{MODULE/./-}.html#%{NAME},libraries/pretty/dist-install/doc/html/pretty/pretty.haddock --optghc=-hisuf --optghc=dyn_hi --optghc=-osuf --optghc=dyn_o --optghc=-hcsuf --optghc=dyn_hc --optghc=-fPIC --optghc=-dynamic --optghc=-H32m --optghc=-O --optghc=-this-package-key --optghc=templ_1ejK907jvoTHoZ6iZtHeyN --optghc=-hide-all-packages --optghc=-i --optghc=-ilibraries/template-haskell/. --optghc=-ilibraries/template-haskell/dist-install/build --optghc=-ilibraries/template-haskell/dist-install/build/autogen --optghc=-Ilibraries/template-haskell/dist-install/build --optghc=-Ilibraries/template-haskell/dist-install/build/autogen --optghc=-Ilibraries/template-haskell/. --optghc=-optP-include --optghc=-optPlibraries/template-haskell/dist-install/build/autogen/cabal_macros.h --optghc=-package-key --optghc=base_GDytRqRVSUX7zckgKqJjgw --optghc=-package-key --optghc=prett_7UQTOB05U7lIYPkFOVraeR --optghc=-Wall --optghc=-this-package-key --optghc=template-haskell --optghc=-XHaskell2010 --optghc=-O2 --optghc=-no-user-package-db --optghc=-rtsopts --optghc=-odir --optghc=libraries/template-haskell/dist-install/build --optghc=-hidir --optghc=libraries/template-haskell/dist-install/build --optghc=-stubdir --optghc=libraries/template-haskell/dist-install/build --source-module=src/%{MODULE/./-}.html --source-entity=src/%{MODULE/./-}.html#%{NAME} libraries/template-haskell/./Language/Haskell/TH.hs libraries/template-haskell/./Language/Haskell/TH/Lib.hs libraries/template-haskell/./Language/Haskell/TH/Ppr.hs libraries/template-haskell/./Language/Haskell/TH/PprLib.hs libraries/template-haskell/./Language/Haskell/TH/Quote.hs libraries/template-haskell/./Language/Haskell/TH/Syntax.hs libraries/template-haskell/./Language/Haskell/TH/Lib/Map.hs +RTS -tlibraries/template-haskell/dist-install/doc/html/template-haskell/template-haskell.haddock.t --machine-readable 
 [("bytes allocated", "1680433776")
 ,("num_GCs", "2854")
 ,("average_bytes_used", "30057504")
 ,("max_bytes_used", "78384856")
 ,("num_byte_usage_samples", "9")
 ,("peak_megabytes_allocated", "192")
 ,("init_cpu_seconds", "0.001")
 ,("init_wall_seconds", "0.011")
 ,("mutator_cpu_seconds", "2.154")
 ,("mutator_wall_seconds", "3.620")
 ,("GC_cpu_seconds", "2.832")
 ,("GC_wall_seconds", "4.371")
 ]
