libraries/containers_dist-install_VERSION = 0.5.6.2
libraries/containers_dist-install_PACKAGE_KEY = conta_LKCPrTJwOTOLk4OU37YmeN
libraries/containers_dist-install_LIB_NAME = containers-0.5.6.2-LKCPrTJwOTOLk4OU37YmeN
libraries/containers_dist-install_MODULES = Data.IntMap Data.IntMap.Lazy Data.IntMap.Strict Data.IntSet Data.Map Data.Map.Lazy Data.Map.Strict Data.Set Data.Graph Data.Sequence Data.Tree Data.IntMap.Base Data.IntSet.Base Data.Map.Base Data.Set.Base Data.Utils.BitUtil Data.Utils.StrictFold Data.Utils.StrictPair
libraries/containers_dist-install_HIDDEN_MODULES = Data.IntMap.Base Data.IntSet.Base Data.Map.Base Data.Set.Base Data.Utils.BitUtil Data.Utils.StrictFold Data.Utils.StrictPair
libraries/containers_dist-install_SYNOPSIS =Assorted concrete container types
libraries/containers_dist-install_HS_SRC_DIRS = .
libraries/containers_dist-install_DEPS = array-0.5.1.0 base-4.8.1.0 deepseq-1.4.1.1 ghc-prim-0.4.0.0
libraries/containers_dist-install_DEP_KEYS = array_E0sTtauuKsGDLZoT7lTbgZ base_GDytRqRVSUX7zckgKqJjgw deeps_LbCWUlehDDeLxurARKDH5o ghcpr_8TmvWUcS1U1IKHT0levwg3
libraries/containers_dist-install_DEP_NAMES = array base deepseq ghc-prim
libraries/containers_dist-install_TRANSITIVE_DEPS = deepseq-1.4.1.1 array-0.5.1.0 base-4.8.1.0 integer-gmp-1.0.0.0 ghc-prim-0.4.0.0 rts-1.0
libraries/containers_dist-install_TRANSITIVE_DEP_KEYS = deeps_LbCWUlehDDeLxurARKDH5o array_E0sTtauuKsGDLZoT7lTbgZ base_GDytRqRVSUX7zckgKqJjgw integ_2aU3IZNMF9a7mQ0OzsZ0dS ghcpr_8TmvWUcS1U1IKHT0levwg3 rts
libraries/containers_dist-install_TRANSITIVE_DEP_NAMES = deepseq array base integer-gmp ghc-prim rts
libraries/containers_dist-install_INCLUDE_DIRS = include
libraries/containers_dist-install_INCLUDES = 
libraries/containers_dist-install_INSTALL_INCLUDES = 
libraries/containers_dist-install_EXTRA_LIBRARIES = 
libraries/containers_dist-install_EXTRA_LIBDIRS = 
libraries/containers_dist-install_C_SRCS  = 
libraries/containers_dist-install_CMM_SRCS  := $(addprefix cbits/,$(notdir $(wildcard libraries/containers/cbits/*.cmm)))
libraries/containers_dist-install_DATA_FILES = 
libraries/containers_dist-install_HC_OPTS = -O2 -Wall -XHaskell98
libraries/containers_dist-install_CC_OPTS = 
libraries/containers_dist-install_CPP_OPTS = 
libraries/containers_dist-install_LD_OPTS = 
libraries/containers_dist-install_DEP_INCLUDE_DIRS_SINGLE_QUOTED = '/Users/mark/Projects/ghc-7.10.2/libraries/base/include' '/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/include' '/Users/mark/Projects/ghc-7.10.2/rts/dist/build' '/Users/mark/Projects/ghc-7.10.2/includes' '/Users/mark/Projects/ghc-7.10.2/includes/dist-derivedconstants/header'
libraries/containers_dist-install_DEP_CC_OPTS = 
libraries/containers_dist-install_DEP_LIB_DIRS_SINGLE_QUOTED = '/Users/mark/Projects/ghc-7.10.2/libraries/deepseq/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/array/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/base/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/ghc-prim/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/rts/dist/build'
libraries/containers_dist-install_DEP_LIB_DIRS_SEARCHPATH = /Users/mark/Projects/ghc-7.10.2/libraries/deepseq/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/array/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/base/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/ghc-prim/dist-install/build:/Users/mark/Projects/ghc-7.10.2/rts/dist/build
libraries/containers_dist-install_DEP_LIB_REL_DIRS = libraries/deepseq/dist-install/build libraries/array/dist-install/build libraries/base/dist-install/build libraries/integer-gmp2/dist-install/build libraries/ghc-prim/dist-install/build rts/dist/build
libraries/containers_dist-install_DEP_LIB_REL_DIRS_SEARCHPATH = libraries/deepseq/dist-install/build:libraries/array/dist-install/build:libraries/base/dist-install/build:libraries/integer-gmp2/dist-install/build:libraries/ghc-prim/dist-install/build:rts/dist/build
libraries/containers_dist-install_DEP_EXTRA_LIBS = iconv m dl
libraries/containers_dist-install_DEP_LD_OPTS = 
libraries/containers_dist-install_BUILD_GHCI_LIB = NO

$(eval $(libraries/containers_PACKAGE_MAGIC))
