libraries/hoopl_dist-install_VERSION = 3.10.0.2
libraries/hoopl_dist-install_PACKAGE_KEY = hoopl_DoMsb793VEWGUzPylcUNJi
libraries/hoopl_dist-install_LIB_NAME = hoopl-3.10.0.2-DoMsb793VEWGUzPylcUNJi
libraries/hoopl_dist-install_MODULES = Compiler.Hoopl Compiler.Hoopl.Internals Compiler.Hoopl.Wrappers Compiler.Hoopl.Passes.Dominator Compiler.Hoopl.Passes.DList Compiler.Hoopl.Checkpoint Compiler.Hoopl.Collections Compiler.Hoopl.Combinators Compiler.Hoopl.Dataflow Compiler.Hoopl.Debug Compiler.Hoopl.Block Compiler.Hoopl.Graph Compiler.Hoopl.Label Compiler.Hoopl.MkGraph Compiler.Hoopl.Fuel Compiler.Hoopl.Pointed Compiler.Hoopl.Shape Compiler.Hoopl.Show Compiler.Hoopl.Unique Compiler.Hoopl.XUtil
libraries/hoopl_dist-install_HIDDEN_MODULES = Compiler.Hoopl.Checkpoint Compiler.Hoopl.Collections Compiler.Hoopl.Combinators Compiler.Hoopl.Dataflow Compiler.Hoopl.Debug Compiler.Hoopl.Block Compiler.Hoopl.Graph Compiler.Hoopl.Label Compiler.Hoopl.MkGraph Compiler.Hoopl.Fuel Compiler.Hoopl.Pointed Compiler.Hoopl.Shape Compiler.Hoopl.Show Compiler.Hoopl.Unique Compiler.Hoopl.XUtil
libraries/hoopl_dist-install_SYNOPSIS =A library to support dataflow analysis and optimization
libraries/hoopl_dist-install_HS_SRC_DIRS = src
libraries/hoopl_dist-install_DEPS = base-4.8.1.0 containers-0.5.6.2
libraries/hoopl_dist-install_DEP_KEYS = base_GDytRqRVSUX7zckgKqJjgw conta_LKCPrTJwOTOLk4OU37YmeN
libraries/hoopl_dist-install_DEP_NAMES = base containers
libraries/hoopl_dist-install_TRANSITIVE_DEPS = containers-0.5.6.2 deepseq-1.4.1.1 array-0.5.1.0 base-4.8.1.0 integer-gmp-1.0.0.0 ghc-prim-0.4.0.0 rts-1.0
libraries/hoopl_dist-install_TRANSITIVE_DEP_KEYS = conta_LKCPrTJwOTOLk4OU37YmeN deeps_LbCWUlehDDeLxurARKDH5o array_E0sTtauuKsGDLZoT7lTbgZ base_GDytRqRVSUX7zckgKqJjgw integ_2aU3IZNMF9a7mQ0OzsZ0dS ghcpr_8TmvWUcS1U1IKHT0levwg3 rts
libraries/hoopl_dist-install_TRANSITIVE_DEP_NAMES = containers deepseq array base integer-gmp ghc-prim rts
libraries/hoopl_dist-install_INCLUDE_DIRS = 
libraries/hoopl_dist-install_INCLUDES = 
libraries/hoopl_dist-install_INSTALL_INCLUDES = 
libraries/hoopl_dist-install_EXTRA_LIBRARIES = 
libraries/hoopl_dist-install_EXTRA_LIBDIRS = 
libraries/hoopl_dist-install_C_SRCS  = 
libraries/hoopl_dist-install_CMM_SRCS  := $(addprefix cbits/,$(notdir $(wildcard libraries/hoopl/cbits/*.cmm)))
libraries/hoopl_dist-install_DATA_FILES = 
libraries/hoopl_dist-install_HC_OPTS = -Wall -fno-warn-name-shadowing -XHaskell2010
libraries/hoopl_dist-install_CC_OPTS = 
libraries/hoopl_dist-install_CPP_OPTS = 
libraries/hoopl_dist-install_LD_OPTS = 
libraries/hoopl_dist-install_DEP_INCLUDE_DIRS_SINGLE_QUOTED = '/Users/mark/Projects/ghc-7.10.2/libraries/containers/include' '/Users/mark/Projects/ghc-7.10.2/libraries/base/include' '/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/include' '/Users/mark/Projects/ghc-7.10.2/rts/dist/build' '/Users/mark/Projects/ghc-7.10.2/includes' '/Users/mark/Projects/ghc-7.10.2/includes/dist-derivedconstants/header'
libraries/hoopl_dist-install_DEP_CC_OPTS = 
libraries/hoopl_dist-install_DEP_LIB_DIRS_SINGLE_QUOTED = '/Users/mark/Projects/ghc-7.10.2/libraries/containers/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/deepseq/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/array/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/base/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/ghc-prim/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/rts/dist/build'
libraries/hoopl_dist-install_DEP_LIB_DIRS_SEARCHPATH = /Users/mark/Projects/ghc-7.10.2/libraries/containers/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/deepseq/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/array/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/base/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/ghc-prim/dist-install/build:/Users/mark/Projects/ghc-7.10.2/rts/dist/build
libraries/hoopl_dist-install_DEP_LIB_REL_DIRS = libraries/containers/dist-install/build libraries/deepseq/dist-install/build libraries/array/dist-install/build libraries/base/dist-install/build libraries/integer-gmp2/dist-install/build libraries/ghc-prim/dist-install/build rts/dist/build
libraries/hoopl_dist-install_DEP_LIB_REL_DIRS_SEARCHPATH = libraries/containers/dist-install/build:libraries/deepseq/dist-install/build:libraries/array/dist-install/build:libraries/base/dist-install/build:libraries/integer-gmp2/dist-install/build:libraries/ghc-prim/dist-install/build:rts/dist/build
libraries/hoopl_dist-install_DEP_EXTRA_LIBS = iconv m dl
libraries/hoopl_dist-install_DEP_LD_OPTS = 
libraries/hoopl_dist-install_BUILD_GHCI_LIB = NO

$(eval $(libraries/hoopl_PACKAGE_MAGIC))
