libraries/directory_dist-install_VERSION = 1.2.2.0
libraries/directory_dist-install_PACKAGE_KEY = direc_KowvXytSqazBcvN7MGpFtg
libraries/directory_dist-install_LIB_NAME = directory-1.2.2.0-KowvXytSqazBcvN7MGpFtg
libraries/directory_dist-install_MODULES = System.Directory
libraries/directory_dist-install_HIDDEN_MODULES = 
libraries/directory_dist-install_SYNOPSIS =Platform-agnostic library for filesystem operations
libraries/directory_dist-install_HS_SRC_DIRS = .
libraries/directory_dist-install_DEPS = base-4.8.1.0 filepath-1.4.0.0 time-1.5.0.1 unix-2.7.1.0
libraries/directory_dist-install_DEP_KEYS = base_GDytRqRVSUX7zckgKqJjgw filep_KsGE6pHE5eZHSN90ZVax6A time_AXTdBF9VRQoBOqJT6qtmVH unix_A3WgcI5QiHK4PDo4jSYdwQ
libraries/directory_dist-install_DEP_NAMES = base filepath time unix
libraries/directory_dist-install_TRANSITIVE_DEPS = unix-2.7.1.0 time-1.5.0.1 filepath-1.4.0.0 bytestring-0.10.6.0 deepseq-1.4.1.1 array-0.5.1.0 base-4.8.1.0 integer-gmp-1.0.0.0 ghc-prim-0.4.0.0 rts-1.0
libraries/directory_dist-install_TRANSITIVE_DEP_KEYS = unix_A3WgcI5QiHK4PDo4jSYdwQ time_AXTdBF9VRQoBOqJT6qtmVH filep_KsGE6pHE5eZHSN90ZVax6A bytes_6elQVSg5cWdFrvRnfxTUrH deeps_LbCWUlehDDeLxurARKDH5o array_E0sTtauuKsGDLZoT7lTbgZ base_GDytRqRVSUX7zckgKqJjgw integ_2aU3IZNMF9a7mQ0OzsZ0dS ghcpr_8TmvWUcS1U1IKHT0levwg3 rts
libraries/directory_dist-install_TRANSITIVE_DEP_NAMES = unix time filepath bytestring deepseq array base integer-gmp ghc-prim rts
libraries/directory_dist-install_INCLUDE_DIRS = include
libraries/directory_dist-install_INCLUDES = HsDirectory.h
libraries/directory_dist-install_INSTALL_INCLUDES = HsDirectoryConfig.h HsDirectory.h
libraries/directory_dist-install_EXTRA_LIBRARIES = 
libraries/directory_dist-install_EXTRA_LIBDIRS = 
libraries/directory_dist-install_C_SRCS  = cbits/directory.c
libraries/directory_dist-install_CMM_SRCS  := $(addprefix cbits/,$(notdir $(wildcard libraries/directory/cbits/*.cmm)))
libraries/directory_dist-install_DATA_FILES = 
libraries/directory_dist-install_HC_OPTS = -Wall -XHaskell2010
libraries/directory_dist-install_CC_OPTS = 
libraries/directory_dist-install_CPP_OPTS = 
libraries/directory_dist-install_LD_OPTS = 
libraries/directory_dist-install_DEP_INCLUDE_DIRS_SINGLE_QUOTED = '/Users/mark/Projects/ghc-7.10.2/libraries/unix/include' '/Users/mark/Projects/ghc-7.10.2/libraries/time/lib/include' '/Users/mark/Projects/ghc-7.10.2/libraries/bytestring/include' '/Users/mark/Projects/ghc-7.10.2/libraries/base/include' '/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/include' '/Users/mark/Projects/ghc-7.10.2/rts/dist/build' '/Users/mark/Projects/ghc-7.10.2/includes' '/Users/mark/Projects/ghc-7.10.2/includes/dist-derivedconstants/header'
libraries/directory_dist-install_DEP_CC_OPTS = 
libraries/directory_dist-install_DEP_LIB_DIRS_SINGLE_QUOTED = '/Users/mark/Projects/ghc-7.10.2/libraries/unix/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/time/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/filepath/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/bytestring/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/deepseq/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/array/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/base/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/ghc-prim/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/rts/dist/build'
libraries/directory_dist-install_DEP_LIB_DIRS_SEARCHPATH = /Users/mark/Projects/ghc-7.10.2/libraries/unix/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/time/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/filepath/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/bytestring/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/deepseq/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/array/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/base/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/ghc-prim/dist-install/build:/Users/mark/Projects/ghc-7.10.2/rts/dist/build
libraries/directory_dist-install_DEP_LIB_REL_DIRS = libraries/unix/dist-install/build libraries/time/dist-install/build libraries/filepath/dist-install/build libraries/bytestring/dist-install/build libraries/deepseq/dist-install/build libraries/array/dist-install/build libraries/base/dist-install/build libraries/integer-gmp2/dist-install/build libraries/ghc-prim/dist-install/build rts/dist/build
libraries/directory_dist-install_DEP_LIB_REL_DIRS_SEARCHPATH = libraries/unix/dist-install/build:libraries/time/dist-install/build:libraries/filepath/dist-install/build:libraries/bytestring/dist-install/build:libraries/deepseq/dist-install/build:libraries/array/dist-install/build:libraries/base/dist-install/build:libraries/integer-gmp2/dist-install/build:libraries/ghc-prim/dist-install/build:rts/dist/build
libraries/directory_dist-install_DEP_EXTRA_LIBS = iconv m dl
libraries/directory_dist-install_DEP_LD_OPTS = 
libraries/directory_dist-install_BUILD_GHCI_LIB = NO

$(eval $(libraries/directory_PACKAGE_MAGIC))
