libraries/terminfo_dist-install_VERSION = 0.4.0.1
libraries/terminfo_dist-install_PACKAGE_KEY = termi_KvtqTNXWuWjKicEYaZ7qsx
libraries/terminfo_dist-install_LIB_NAME = terminfo-0.4.0.1-KvtqTNXWuWjKicEYaZ7qsx
libraries/terminfo_dist-install_MODULES = System.Console.Terminfo System.Console.Terminfo.Base System.Console.Terminfo.Cursor System.Console.Terminfo.Color System.Console.Terminfo.Edit System.Console.Terminfo.Effects System.Console.Terminfo.Keys
libraries/terminfo_dist-install_HIDDEN_MODULES = 
libraries/terminfo_dist-install_SYNOPSIS =Haskell bindings to the terminfo library.
libraries/terminfo_dist-install_HS_SRC_DIRS = .
libraries/terminfo_dist-install_DEPS = base-4.8.1.0
libraries/terminfo_dist-install_DEP_KEYS = base_GDytRqRVSUX7zckgKqJjgw
libraries/terminfo_dist-install_DEP_NAMES = base
libraries/terminfo_dist-install_TRANSITIVE_DEPS = base-4.8.1.0 integer-gmp-1.0.0.0 ghc-prim-0.4.0.0 rts-1.0
libraries/terminfo_dist-install_TRANSITIVE_DEP_KEYS = base_GDytRqRVSUX7zckgKqJjgw integ_2aU3IZNMF9a7mQ0OzsZ0dS ghcpr_8TmvWUcS1U1IKHT0levwg3 rts
libraries/terminfo_dist-install_TRANSITIVE_DEP_NAMES = base integer-gmp ghc-prim rts
libraries/terminfo_dist-install_INCLUDE_DIRS = 
libraries/terminfo_dist-install_INCLUDES = ncurses.h term.h
libraries/terminfo_dist-install_INSTALL_INCLUDES = 
libraries/terminfo_dist-install_EXTRA_LIBRARIES = ncurses
libraries/terminfo_dist-install_EXTRA_LIBDIRS = 
libraries/terminfo_dist-install_C_SRCS  = 
libraries/terminfo_dist-install_CMM_SRCS  := $(addprefix cbits/,$(notdir $(wildcard libraries/terminfo/cbits/*.cmm)))
libraries/terminfo_dist-install_DATA_FILES = 
libraries/terminfo_dist-install_HC_OPTS = -Wall -XHaskell2010
libraries/terminfo_dist-install_CC_OPTS = 
libraries/terminfo_dist-install_CPP_OPTS = 
libraries/terminfo_dist-install_LD_OPTS = 
libraries/terminfo_dist-install_DEP_INCLUDE_DIRS_SINGLE_QUOTED = '/Users/mark/Projects/ghc-7.10.2/libraries/base/include' '/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/include' '/Users/mark/Projects/ghc-7.10.2/rts/dist/build' '/Users/mark/Projects/ghc-7.10.2/includes' '/Users/mark/Projects/ghc-7.10.2/includes/dist-derivedconstants/header'
libraries/terminfo_dist-install_DEP_CC_OPTS = 
libraries/terminfo_dist-install_DEP_LIB_DIRS_SINGLE_QUOTED = '/Users/mark/Projects/ghc-7.10.2/libraries/base/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/libraries/ghc-prim/dist-install/build' '/Users/mark/Projects/ghc-7.10.2/rts/dist/build'
libraries/terminfo_dist-install_DEP_LIB_DIRS_SEARCHPATH = /Users/mark/Projects/ghc-7.10.2/libraries/base/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/integer-gmp2/dist-install/build:/Users/mark/Projects/ghc-7.10.2/libraries/ghc-prim/dist-install/build:/Users/mark/Projects/ghc-7.10.2/rts/dist/build
libraries/terminfo_dist-install_DEP_LIB_REL_DIRS = libraries/base/dist-install/build libraries/integer-gmp2/dist-install/build libraries/ghc-prim/dist-install/build rts/dist/build
libraries/terminfo_dist-install_DEP_LIB_REL_DIRS_SEARCHPATH = libraries/base/dist-install/build:libraries/integer-gmp2/dist-install/build:libraries/ghc-prim/dist-install/build:rts/dist/build
libraries/terminfo_dist-install_DEP_EXTRA_LIBS = iconv m dl
libraries/terminfo_dist-install_DEP_LD_OPTS = 
libraries/terminfo_dist-install_BUILD_GHCI_LIB = NO

$(eval $(libraries/terminfo_PACKAGE_MAGIC))
